version: '2'
services:
  jukkirek-app:
    image: jukkirek
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jukkirek-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jukkirek
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jukkirek-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jukkirek-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8090:8090
  jukkirek-mongodb:
    extends:
      file: mongodb.yml
      service: jukkirek-mongodb
  jukkirek-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jukkirek-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
